binary.drawBinary(0, 1)
binary.drawBinary(1, 2)
binary.drawBinary(2, 3)
binary.drawBinary(3, 4)
binary.drawBinary(4, 5)
basic.pause(2000)
basic.clearScreen()
binary.drawBinary(0, 6)
binary.drawBinary(1, 7)
binary.drawBinary(2, 8)
binary.drawBinary(3, 9)
binary.drawBinary(4, 0)
