Binary.drawBinary(0, 1)
Binary.drawBinary(1, 2)
Binary.drawBinary(2, 3)
Binary.drawBinary(3, 4)
Binary.drawBinary(4, 5)
basic.pause(2000)
basic.clearScreen()
Binary.drawBinary(0, 6)
Binary.drawBinary(1, 7)
Binary.drawBinary(2, 8)
Binary.drawBinary(3, 9)
Binary.drawBinary(4, 0)